apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  namespace: devops-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
      # ── ESTAS 3 LÍNEAS LE DAN "OJOS" A PROMETHEUS ──
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: petclinic
        image: ghcr.io/stevenismael/spring-petclinic-devops:073593aaa7e2342cfe55b67647fbb4cc1080449f
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10