---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
  namespace: devops-lab
  labels:
    app: petclinic
spec:
  type: LoadBalancer
  selector:
    app: petclinic
  ports:
    - name: web  # Le damos un nombre al puerto para que Prometheus lo encuentre
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: petclinic-hpa
  namespace: devops-lab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: petclinic
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: petclinic-monitor
  namespace: monitoring
  labels:
    # Esta etiqueta es la llave mágica. Hace que el Operador de Prometheus lo adopte.
    release: prom
spec:
  selector:
    matchLabels:
      app: petclinic
  namespaceSelector:
    matchNames:
      - devops-lab
  endpoints:
  - port: web
    path: /actuator/prometheus
    interval: 15s